import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import React from 'react';
import { Link } from 'react-router-dom';
import { EyeIcon, PencilIcon, TrashIcon, ExclamationTriangleIcon, CheckCircleIcon } from '@heroicons/react/24/outline';
import { cn } from '@/utils/cn';
const ProductCard = ({ product }) => {
    const isLowStock = product.inventory &&
        product.inventory.stockQuantity <= product.inventory.minStockLevel;
    const syncedMarketplaces = product.marketplaceProducts?.filter(mp => mp.syncStatus === 'SUCCESS').length || 0;
    const totalMarketplaces = product.marketplaceProducts?.length || 0;
    return (_jsxs("div", { className: "bg-white border border-gray-200 rounded-lg overflow-hidden hover:shadow-md transition-shadow", children: [_jsx("div", { className: "aspect-w-1 aspect-h-1 w-full overflow-hidden bg-gray-200", children: product.images && product.images.length > 0 ? (_jsx("img", { src: product.images[0], alt: product.name, className: "h-48 w-full object-cover object-center group-hover:opacity-75" })) : (_jsx("div", { className: "h-48 w-full flex items-center justify-center bg-gray-100", children: _jsx("svg", { className: "h-12 w-12 text-gray-400", fill: "none", viewBox: "0 0 24 24", stroke: "currentColor", children: _jsx("path", { strokeLinecap: "round", strokeLinejoin: "round", strokeWidth: 1, d: "M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z" }) }) })) }), _jsxs("div", { className: "p-4", children: [_jsxs("div", { className: "flex items-start justify-between", children: [_jsxs("div", { className: "flex-1 min-w-0", children: [_jsx("h3", { className: "text-sm font-medium text-gray-900 truncate", children: product.name }), _jsxs("p", { className: "text-sm text-gray-500 mt-1", children: ["SKU: ", product.sku] }), product.category && (_jsx("p", { className: "text-xs text-gray-400 mt-1", children: product.category.name }))] }), _jsxs("div", { className: "flex flex-col items-end space-y-1", children: [_jsx("span", { className: cn('inline-flex items-center px-2 py-1 rounded-full text-xs font-medium', product.isActive
                                            ? 'bg-green-100 text-green-800'
                                            : 'bg-red-100 text-red-800'), children: product.isActive ? 'Aktif' : 'Nonaktif' }), isLowStock && (_jsxs("span", { className: "inline-flex items-center px-2 py-1 rounded-full text-xs font-medium bg-yellow-100 text-yellow-800", children: [_jsx(ExclamationTriangleIcon, { className: "h-3 w-3 mr-1" }), "Stok Rendah"] }))] })] }), _jsxs("div", { className: "mt-3", children: [_jsxs("div", { className: "flex items-center justify-between", children: [_jsxs("span", { className: "text-lg font-semibold text-gray-900", children: ["Rp ", product.price?.toLocaleString('id-ID')] }), _jsxs("span", { className: cn('text-sm font-medium', isLowStock ? 'text-red-600' : 'text-gray-600'), children: ["Stok: ", product.inventory?.stockQuantity || 0] })] }), product._count?.variants && product._count.variants > 0 && (_jsxs("p", { className: "text-xs text-gray-500 mt-1", children: [product._count.variants, " varian"] }))] }), totalMarketplaces > 0 && (_jsxs("div", { className: "mt-3 pt-3 border-t border-gray-100", children: [_jsxs("div", { className: "flex items-center justify-between", children: [_jsx("span", { className: "text-xs text-gray-500", children: "Marketplace:" }), _jsxs("div", { className: "flex items-center space-x-1", children: [syncedMarketplaces === totalMarketplaces ? (_jsx(CheckCircleIcon, { className: "h-4 w-4 text-green-500" })) : (_jsx(ExclamationTriangleIcon, { className: "h-4 w-4 text-yellow-500" })), _jsxs("span", { className: "text-xs text-gray-600", children: [syncedMarketplaces, "/", totalMarketplaces] })] })] }), _jsxs("div", { className: "flex flex-wrap gap-1 mt-2", children: [product.marketplaceProducts?.slice(0, 3).map((mp, index) => (_jsx("span", { className: cn('inline-flex items-center px-2 py-1 rounded text-xs font-medium', mp.syncStatus === 'SUCCESS'
                                            ? 'bg-green-100 text-green-700'
                                            : mp.syncStatus === 'FAILED'
                                                ? 'bg-red-100 text-red-700'
                                                : 'bg-yellow-100 text-yellow-700'), children: mp.marketplace.name }, index))), totalMarketplaces > 3 && (_jsxs("span", { className: "text-xs text-gray-500", children: ["+", totalMarketplaces - 3] }))] })] })), _jsxs("div", { className: "mt-4 flex items-center justify-between", children: [_jsx(Link, { to: `/products/${product.id}`, className: "text-primary-600 hover:text-primary-500 text-sm font-medium", children: "Lihat Detail" }), _jsxs("div", { className: "flex items-center space-x-2", children: [_jsx(Link, { to: `/products/${product.id}`, className: "p-1 text-gray-400 hover:text-gray-600", title: "Lihat", children: _jsx(EyeIcon, { className: "h-4 w-4" }) }), _jsx(Link, { to: `/products/${product.id}/edit`, className: "p-1 text-gray-400 hover:text-gray-600", title: "Edit", children: _jsx(PencilIcon, { className: "h-4 w-4" }) }), _jsx("button", { type: "button", className: "p-1 text-gray-400 hover:text-red-600", title: "Hapus", children: _jsx(TrashIcon, { className: "h-4 w-4" }) })] })] })] })] }));
};
export default ProductCard;
//# sourceMappingURL=ProductCard.js.map